config/routes.rb
::Refinery::Application.routes.draw do
  scope(:path => 'whatson', :module => 'whatson') do
    root :to => 'posts#index', :as => 'whatson_root'
    match 'feed.rss', :to => 'posts#index', :as => 'whatson_rss_feed', :defaults => {:format => "rss"}
    match ':id', :to => 'posts#show', :as => 'whatson_post'
    match 'categories/:id', :to => 'categories#show', :as => 'whatson_category'
    match ':id/comments', :to => 'posts#comment', :as => 'whatson_post_whatson_comments'
    get 'archive/:year(/:month)', :to => 'posts#archive', :as => 'archive_whatson_posts'
    get 'tagged/:tag_id(/:tag_name)' => 'posts#tagged', :as => 'tagged_posts'
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    scope(:path => 'whatson', :as => 'whatson', :module => 'whatson') do
      root :to => 'posts#index'
      resources :posts do
        collection do
          get :uncategorized
          get :tags
        end
      end

      resources :categories

      resources :comments do
        collection do
          get :approved
          get :rejected
        end
        member do
          get :approved
          get :rejected
        end
      end

      resources :settings do
        collection do
          get :notification_recipients
          post :notification_recipients

          get :moderation
          get :comments
          get :teasers
        end
      end
    end
  end
end

app/models/whatson/comment_mailer.rb
require File.expand_path('../../../mailers/whatson/comment_mailer', __FILE__)

app/controllers/admin/whatson/categories_controller.rb
module Admin
  module Whatson
    class CategoriesController < Admin::BaseController

      crudify :whatson_category,
              :title_attribute => :title,
              :order => 'title ASC'

    end
  end
end

app/controllers/admin/whatson/comments_controller.rb
module Admin
  module Whatson
    class CommentsController < Admin::BaseController

      crudify :whatson_comment,
              :title_attribute => :name,
              :order => 'published_at DESC'

      def index
        @whatson_comments = WhatsonComment.unmoderated
        render :action => 'index'
      end

      def approved
        unless params[:id].present?
          @whatson_comments = WhatsonComment.approved
          render :action => 'index'
        else
          @whatson_comment = WhatsonComment.find(params[:id])
          @whatson_comment.approve!
          flash[:notice] = t('approved', :scope => 'admin.whatson.comments', :author => @whatson_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

      def rejected
        unless params[:id].present?
          @whatson_comments = WhatsonComment.rejected
          render :action => 'index'
        else
          @whatson_comment = WhatsonComment.find(params[:id])
          @whatson_comment.reject!
          flash[:notice] = t('rejected', :scope => 'admin.whatson.comments', :author => @whatson_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

    end
  end
end

app/controllers/admin/whatson/posts_controller.rb
module Admin
  module Whatson
    class PostsController < Admin::BaseController
      require 'will_paginate/array'
      
      crudify :whatson_post,
              :title_attribute => :title,
              :order => 'published_at DESC'
          
      def uncategorized
        @whatson_posts = WhatsonPost.uncategorized.paginate({
          :page => params[:page],
          :per_page => WhatsonPost.per_page
        })
      end
  
      def tags
        op =  case ActiveRecord::Base.connection.adapter_name.downcase
              when 'postgresql'
                '~*'
              else
                'LIKE'
              end
        wildcard =  case ActiveRecord::Base.connection.adapter_name.downcase
                    when 'postgresql'
                      '.*'
                    else
                      '%'
                    end
        @tags = WhatsonPost.tag_counts_on(:tags).where(
            ["tags.name #{op} ?", "#{wildcard}#{params[:term].to_s.downcase}#{wildcard}"]
          ).map { |tag| {:id => tag.id, :value => tag.name}}
        render :json => @tags.flatten
      end
  
      def create
        # if the position field exists, set this object as last object, given the conditions of this class.
        if WhatsonPost.column_names.include?("position")
          params[:whatson_post].merge!({
            :position => ((WhatsonPost.maximum(:position, :conditions => "")||-1) + 1)
          })
        end
    
        if WhatsonPost.column_names.include?("user_id")
          params[:whatson_post].merge!({
            :user_id => current_user.id
          })
        end

        if (@whatson_post = WhatsonPost.create(params[:whatson_post])).valid?
          (request.xhr? ? flash.now : flash).notice = t(
            'refinery.crudify.created',
            :what => "'#{@whatson_post.title}'"
          )

          unless from_dialog?
            unless params[:continue_editing] =~ /true|on|1/
              redirect_back_or_default(admin_whatson_posts_url)
            else
              unless request.xhr?
                redirect_to :back
              else
                render :partial => "/shared/message"
              end
            end
          else
            render :text => "<script>parent.window.location = '#{admin_whatson_posts_url}';</script>"
          end
        else
          unless request.xhr?
            render :action => 'new'
          else
            render :partial => "/shared/admin/error_messages",
                   :locals => {
                     :object => @whatson_post,
                     :include_object_name => true
                   }
          end
        end
      end

      before_filter :find_all_categories,
                    :only => [:new, :edit, :create, :update]

      before_filter :check_category_ids, :only => :update

    protected
      def find_all_categories
        @whatson_categories = WhatsonCategory.find(:all)
      end

      def check_category_ids
        params[:whatson_post][:category_ids] ||= []
      end
    end
  end
end

app/controllers/admin/whatson/settings_controller.rb
module Admin
  module Whatson
    class SettingsController < Admin::BaseController

      def notification_recipients
        @recipients = WhatsonComment::Notification.recipients

        if request.post?
          WhatsonComment::Notification.recipients = params[:recipients]
          flash[:notice] = t('updated', :scope => 'admin.whatson.settings.notification_recipients',
                             :recipients => WhatsonComment::Notification.recipients)
          unless request.xhr? or from_dialog?
            redirect_back_or_default(admin_whatson_posts_path)
          else
            render :text => "<script type='text/javascript'>parent.window.location = '#{admin_whatson_posts_path}';</script>",
                   :layout => false
          end
        end
      end

      def moderation
        enabled = WhatsonComment::Moderation.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

      def comments
        enabled = WhatsonComment.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end
      
      def teasers
        enabled = WhatsonPost.teaser_enabled_toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

    end
  end
end

app/controllers/whatson/categories_controller.rb
module Whatson
  class CategoriesController < WhatsonController

    def show
      @category = WhatsonCategory.find(params[:id])
      @whatson_posts = @category.posts.live.includes(:comments, :categories).paginate({
        :page => params[:page],
        :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
      })
    end

  end
end

app/controllers/whatson/posts_controller.rb
module Whatson
  class PostsController < WhatsonController

    before_filter :find_all_whatson_posts, :except => [:archive]
    before_filter :find_whatson_post, :only => [:show, :comment, :update_nav]
    before_filter :find_tags

    respond_to :html, :js, :rss

    def index
      # Rss feeders are greedy. Let's give them every whatson post instead of paginating.
      (@whatson_posts = WhatsonPost.live.includes(:comments, :categories).all) if request.format.rss?
      respond_with (@whatson_posts) do |format|
        format.html
        format.rss
      end
    end

    def show
      @whatson_comment = WhatsonComment.new
      @canonical = url_for(:locale => ::Refinery::I18n.default_frontend_locale) if canonical?

      respond_with (@whatson_post) do |format|
        format.html { present(@whatson_post) }
        format.js { render :partial => 'post', :layout => false }
      end
    end

    def comment
      if (@whatson_comment = @whatson_post.comments.create(params[:whatson_comment])).valid?
        if WhatsonComment::Moderation.enabled? or @whatson_comment.ham?
          begin
            Whatson::CommentMailer.notification(@whatson_comment, request).deliver
          rescue
            logger.warn "There was an error delivering a whatson comment notification.\n#{$!}\n"
          end
        end

        if WhatsonComment::Moderation.enabled?
          flash[:notice] = t('thank_you_moderated', :scope => 'whatson.posts.comments')
          redirect_to whatson_post_url(params[:id])
        else
          flash[:notice] = t('thank_you', :scope => 'whatson.posts.comments')
          redirect_to whatson_post_url(params[:id],
                                   :anchor => "comment-#{@whatson_comment.to_param}")
        end
      else
        render :action => 'show'
      end
    end

    def archive
      if params[:month].present?
        date = "#{params[:month]}/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%B %Y')
        @whatson_posts = WhatsonPost.live.by_archive(@archive_date).paginate({
                                                                               :page => params[:page],
                                                                               :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                             })
      else
        date = "01/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%Y')
        @whatson_posts = WhatsonPost.live.by_year(@archive_date).paginate({
                                                                            :page => params[:page],
                                                                            :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                          })
      end
      respond_with (@whatson_posts)
    end

    def tagged
      @tag = ActsAsTaggableOn::Tag.find(params[:tag_id])
      @tag_name = @tag.name
      @whatson_posts = WhatsonPost.tagged_with(@tag_name).paginate({
                                                                     :page => params[:page],
                                                                     :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                   })
    end

    protected

    def find_whatson_post
      unless (@whatson_post = WhatsonPost.find(params[:id])).try(:live?)
        if refinery_user? and current_user.authorized_plugins.include?("refinerycms_whatson")
          @whatson_post = WhatsonPost.find(params[:id])
        else
          error_404
        end
      end
    end

    def find_all_whatson_posts
      @whatson_posts = WhatsonPost.live.includes(:comments, :categories).paginate({
                                                                                    :page => params[:page],
                                                                                    :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                                  })
    end

    def find_tags
      @tags = WhatsonPost.tag_counts_on(:tags)
    end

    def canonical?
      ::Refinery.i18n_enabled? && ::Refinery::I18n.default_frontend_locale != ::Refinery::I18n.current_frontend_locale
    end
  end
end

app/controllers/whatson_controller.rb
class WhatsonController < ApplicationController

  helper :whatson_posts
  before_filter :find_page, :find_all_whatson_categories

protected

  def find_page
    @page = Page.find_by_link_url("/whatson")
  end

  def find_all_whatson_categories
    @whatson_categories = WhatsonCategory.all
  end

end

app/views/admin/whatson/_submenu.html.erb
<nav id='actions' class='multilist'>
  <ul class='search_list'>
    <li class='not_a_link'>
      <%= render :partial => "/shared/admin/search",
                 :locals => {
                   :url => admin_whatson_posts_url
                 } %>
    </li>
  </ul>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.posts.title'), '#',
                   :class => 'page_copy_icon' %>
    </li>
    <li>
      <%= link_to t('.posts.manage'), admin_whatson_posts_path,
                   :class => 'page_icon' %>
    </li>
    <li>
      <%= link_to t('.posts.uncategorized'), uncategorized_admin_whatson_posts_url,
                  :class => 'page_icon' %>
    </li>
    <li>
       <%= link_to t('.posts.new'), new_admin_whatson_post_url,
                   :class => 'page_add_icon' %>
    </li>
  </ul>
  <% if WhatsonPost.comments_allowed? %>
    <ul class='collapsible_menu'>
      <li class='not_a_link'>
        <% if WhatsonComment.unmoderated.any? %>
          <% title = t('.comments.title_with_count', :new_count => WhatsonComment.unmoderated.size) %>
        <% else %>
          <% title = t('.comments.title') %>
        <% end %>
        <%= link_to title, '#',
                    :class => 'comments_icon' %>
      </li>
      <li>
        <%= link_to t('.comments.new'), admin_whatson_comments_path,
                    :class => 'comment_icon' %>
      </li>
      <li>
        <%= link_to t('.comments.approved'), approved_admin_whatson_comments_path,
                    :class => 'comment_tick_icon' %>
      </li>
      <li>
        <%= link_to t('.comments.rejected'), rejected_admin_whatson_comments_path,
                    :class => 'comment_cross_icon' %>
      </li>
    </ul>
  <% end %>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.categories.title'), '#',
                  :class => 'folder_icon' %>
    </li>
    <li>
      <%= link_to t('.categories.manage'), admin_whatson_categories_url,
                  :class => 'folder_edit_icon' %>
    </li>
    <li>
      <%= link_to t('.categories.new'), new_admin_whatson_category_url(:dialog => true, :height => 325),
                  :class => 'folder_add_icon' %>
    </li>
  </ul>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.settings.title'), admin_whatson_settings_path,
                  :class => 'settings_icon' %>
    </li>
    <li>
      <%= link_to t('.settings.comments'), comments_admin_whatson_settings_url,
                  :class => "#{WhatsonPost.comments_allowed? ? 'success' : 'failure'}_icon" %>
    </li>
    <li>
      <%= link_to t('.settings.moderation'), moderation_admin_whatson_settings_url,
                  :class => "#{WhatsonComment::Moderation.enabled? ? 'success' : 'failure'}_icon" %>
    </li>
    <li>
      <%= link_to t('.settings.update_notified'),
                  notification_recipients_admin_whatson_settings_url(:dialog => true, :height => 400),
                  :class => 'user_comment_icon' %>
    </li>
    <li>
      <%= link_to t('.settings.teasers'),
                  teasers_admin_whatson_settings_url, :class => "#{WhatsonPost.teasers_enabled? ? 'success' : 'failure'}_icon" %>
    </li>
  </ul>

</nav>

<% content_for :stylesheets, stylesheet_link_tag('refinery/refinerycms-whatson')%>