config/routes.rb
::Refinery::Application.routes.draw do
  scope(:path => 'whatson', :module => 'whatson') do
    root :to => 'posts#index', :as => 'whatson_root'
    match 'feed.rss', :to => 'posts#index', :as => 'whatson_rss_feed', :defaults => {:format => "rss"}
    match ':id', :to => 'posts#show', :as => 'whatson_post'
    match 'categories/:id', :to => 'categories#show', :as => 'whatson_category'
    match ':id/comments', :to => 'posts#comment', :as => 'whatson_post_whatson_comments'
    get 'archive/:year(/:month)', :to => 'posts#archive', :as => 'archive_whatson_posts'
    get 'tagged/:tag_id(/:tag_name)' => 'posts#tagged', :as => 'tagged_posts'
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    scope(:path => 'whatson', :as => 'whatson', :module => 'whatson') do
      root :to => 'posts#index'
      resources :posts do
        collection do
          get :uncategorized
          get :tags
        end
      end

      resources :categories

      resources :comments do
        collection do
          get :approved
          get :rejected
        end
        member do
          get :approved
          get :rejected
        end
      end

      resources :settings do
        collection do
          get :notification_recipients
          post :notification_recipients

          get :moderation
          get :comments
          get :teasers
        end
      end
    end
  end
end

app/models/whatson/comment_mailer.rb
require File.expand_path('../../../mailers/whatson/comment_mailer', __FILE__)

app/controllers/admin/whatson/categories_controller.rb
module Admin
  module Whatson
    class CategoriesController < Admin::BaseController

      crudify :whatson_category,
              :title_attribute => :title,
              :order => 'title ASC'

    end
  end
end

app/controllers/admin/whatson/comments_controller.rb
module Admin
  module Whatson
    class CommentsController < Admin::BaseController

      crudify :whatson_comment,
              :title_attribute => :name,
              :order => 'published_at DESC'

      def index
        @whatson_comments = WhatsonComment.unmoderated
        render :action => 'index'
      end

      def approved
        unless params[:id].present?
          @whatson_comments = WhatsonComment.approved
          render :action => 'index'
        else
          @whatson_comment = WhatsonComment.find(params[:id])
          @whatson_comment.approve!
          flash[:notice] = t('approved', :scope => 'admin.whatson.comments', :author => @whatson_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

      def rejected
        unless params[:id].present?
          @whatson_comments = WhatsonComment.rejected
          render :action => 'index'
        else
          @whatson_comment = WhatsonComment.find(params[:id])
          @whatson_comment.reject!
          flash[:notice] = t('rejected', :scope => 'admin.whatson.comments', :author => @whatson_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

    end
  end
end

app/controllers/admin/whatson/posts_controller.rb
module Admin
  module Whatson
    class PostsController < Admin::BaseController
      require 'will_paginate/array'
      
      crudify :whatson_post,
              :title_attribute => :title,
              :order => 'published_at DESC'
          
      def uncategorized
        @whatson_posts = WhatsonPost.uncategorized.paginate({
          :page => params[:page],
          :per_page => WhatsonPost.per_page
        })
      end
  
      def tags
        op =  case ActiveRecord::Base.connection.adapter_name.downcase
              when 'postgresql'
                '~*'
              else
                'LIKE'
              end
        wildcard =  case ActiveRecord::Base.connection.adapter_name.downcase
                    when 'postgresql'
                      '.*'
                    else
                      '%'
                    end
        @tags = WhatsonPost.tag_counts_on(:tags).where(
            ["tags.name #{op} ?", "#{wildcard}#{params[:term].to_s.downcase}#{wildcard}"]
          ).map { |tag| {:id => tag.id, :value => tag.name}}
        render :json => @tags.flatten
      end
  
      def create
        # if the position field exists, set this object as last object, given the conditions of this class.
        if WhatsonPost.column_names.include?("position")
          params[:whatson_post].merge!({
            :position => ((WhatsonPost.maximum(:position, :conditions => "")||-1) + 1)
          })
        end
    
        if WhatsonPost.column_names.include?("user_id")
          params[:whatson_post].merge!({
            :user_id => current_user.id
          })
        end

        if (@whatson_post = WhatsonPost.create(params[:whatson_post])).valid?
          (request.xhr? ? flash.now : flash).notice = t(
            'refinery.crudify.created',
            :what => "'#{@whatson_post.title}'"
          )

          unless from_dialog?
            unless params[:continue_editing] =~ /true|on|1/
              redirect_back_or_default(admin_whatson_posts_url)
            else
              unless request.xhr?
                redirect_to :back
              else
                render :partial => "/shared/message"
              end
            end
          else
            render :text => "<script>parent.window.location = '#{admin_whatson_posts_url}';</script>"
          end
        else
          unless request.xhr?
            render :action => 'new'
          else
            render :partial => "/shared/admin/error_messages",
                   :locals => {
                     :object => @whatson_post,
                     :include_object_name => true
                   }
          end
        end
      end

      before_filter :find_all_categories,
                    :only => [:new, :edit, :create, :update]

      before_filter :check_category_ids, :only => :update

    protected
      def find_all_categories
        @whatson_categories = WhatsonCategory.find(:all)
      end

      def check_category_ids
        params[:whatson_post][:category_ids] ||= []
      end
    end
  end
end

app/controllers/admin/whatson/settings_controller.rb
module Admin
  module Whatson
    class SettingsController < Admin::BaseController

      def notification_recipients
        @recipients = WhatsonComment::Notification.recipients

        if request.post?
          WhatsonComment::Notification.recipients = params[:recipients]
          flash[:notice] = t('updated', :scope => 'admin.whatson.settings.notification_recipients',
                             :recipients => WhatsonComment::Notification.recipients)
          unless request.xhr? or from_dialog?
            redirect_back_or_default(admin_whatson_posts_path)
          else
            render :text => "<script type='text/javascript'>parent.window.location = '#{admin_whatson_posts_path}';</script>",
                   :layout => false
          end
        end
      end

      def moderation
        enabled = WhatsonComment::Moderation.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

      def comments
        enabled = WhatsonComment.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end
      
      def teasers
        enabled = WhatsonPost.teaser_enabled_toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

    end
  end
end

app/controllers/whatson/categories_controller.rb
module Whatson
  class CategoriesController < WhatsonController

    def show
      @category = WhatsonCategory.find(params[:id])
      @whatson_posts = @category.posts.live.includes(:comments, :categories).paginate({
        :page => params[:page],
        :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
      })
    end

  end
end

app/controllers/whatson/posts_controller.rb
module Whatson
  class PostsController < WhatsonController

    before_filter :find_all_whatson_posts, :except => [:archive]
    before_filter :find_whatson_post, :only => [:show, :comment, :update_nav]
    before_filter :find_tags

    respond_to :html, :js, :rss

    def index
      # Rss feeders are greedy. Let's give them every whatson post instead of paginating.
      (@whatson_posts = WhatsonPost.live.includes(:comments, :categories).all) if request.format.rss?
      respond_with (@whatson_posts) do |format|
        format.html
        format.rss
      end
    end

    def show
      @whatson_comment = WhatsonComment.new
      @canonical = url_for(:locale => ::Refinery::I18n.default_frontend_locale) if canonical?

      respond_with (@whatson_post) do |format|
        format.html { present(@whatson_post) }
        format.js { render :partial => 'post', :layout => false }
      end
    end

    def comment
      if (@whatson_comment = @whatson_post.comments.create(params[:whatson_comment])).valid?
        if WhatsonComment::Moderation.enabled? or @whatson_comment.ham?
          begin
            Whatson::CommentMailer.notification(@whatson_comment, request).deliver
          rescue
            logger.warn "There was an error delivering a whatson comment notification.\n#{$!}\n"
          end
        end

        if WhatsonComment::Moderation.enabled?
          flash[:notice] = t('thank_you_moderated', :scope => 'whatson.posts.comments')
          redirect_to whatson_post_url(params[:id])
        else
          flash[:notice] = t('thank_you', :scope => 'whatson.posts.comments')
          redirect_to whatson_post_url(params[:id],
                                   :anchor => "comment-#{@whatson_comment.to_param}")
        end
      else
        render :action => 'show'
      end
    end

    def archive
      if params[:month].present?
        date = "#{params[:month]}/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%B %Y')
        @whatson_posts = WhatsonPost.live.by_archive(@archive_date).paginate({
                                                                               :page => params[:page],
                                                                               :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                             })
      else
        date = "01/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%Y')
        @whatson_posts = WhatsonPost.live.by_year(@archive_date).paginate({
                                                                            :page => params[:page],
                                                                            :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                          })
      end
      respond_with (@whatson_posts)
    end

    def tagged
      @tag = ActsAsTaggableOn::Tag.find(params[:tag_id])
      @tag_name = @tag.name
      @whatson_posts = WhatsonPost.tagged_with(@tag_name).paginate({
                                                                     :page => params[:page],
                                                                     :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                   })
    end

    protected

    def find_whatson_post
      unless (@whatson_post = WhatsonPost.find(params[:id])).try(:live?)
        if refinery_user? and current_user.authorized_plugins.include?("refinerycms_whatson")
          @whatson_post = WhatsonPost.find(params[:id])
        else
          error_404
        end
      end
    end

    def find_all_whatson_posts
      @whatson_posts = WhatsonPost.live.includes(:comments, :categories).paginate({
                                                                                    :page => params[:page],
                                                                                    :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                                  })
    end

    def find_tags
      @tags = WhatsonPost.tag_counts_on(:tags)
    end

    def canonical?
      ::Refinery.i18n_enabled? && ::Refinery::I18n.default_frontend_locale != ::Refinery::I18n.current_frontend_locale
    end
  end
end

app/controllers/whatson_controller.rb
class WhatsonController < ApplicationController

  helper :whatson_posts
  before_filter :find_page, :find_all_whatson_categories

protected

  def find_page
    @page = Page.find_by_link_url("/whatson")
  end

  def find_all_whatson_categories
    @whatson_categories = WhatsonCategory.all
  end

end

app/views/whatson/posts/_comment.html.erb
<article class='whatson_comment_message' id='<%= "comment-#{comment.to_param}" %>'>
  <%= image_tag comment.avatar_url, :alt => comment.name, :class => 'avatar' %>
  <%= simple_format auto_link(comment.message.to_s) %>
  <footer class='whatson_comment_author'>
    <p>
      <%= t('by', :scope => 'whatson.posts.comments', :who => comment.name) %>,
      <%= t('time_ago', :scope => 'whatson.posts.comments', :time => time_ago_in_words(comment.created_at)) %>
    </p>
  </footer>
</article>

app/views/whatson/posts/_nav.html.erb
<nav id="next_prev_article">
  <% if @whatson_post.next.present? -%>
    <%= link_to (truncate(@whatson_post.next.title) + " &#187;").html_safe, @whatson_post.next, :class => 'next' %>
  <% end -%>

  <%= link_to t('whatson_home', :scope => 'whatson.posts.show'), whatson_root_path, :class => 'home' %>

  <% if @whatson_post.prev.present? -%>
    <%= link_to ("&#171; " + truncate(@whatson_post.prev.title)).html_safe, @whatson_post.prev, :class => 'prev' %>
  <% end -%>
</nav><!-- /next_prev_article -->

app/views/whatson/posts/archive.html.erb
<% content_for :body_content_left do %>
  <h1><%= t('.whatson_archive_for', :date => @archive_date.strftime('%B %Y')) %></h1>
  <% if @whatson_posts.any? %>
    <section id="whatson_posts">
      <%= render :partial => "/whatson/shared/post", :collection => @whatson_posts %>
    </section>
  <% else %>
    <p><%= t('.no_whatson_articles_posted', :date => @archive_date.strftime('%B %Y')) %></p>
  <% end %>
<% end %>

<% content_for :body_content_right do %>
  <%= render :partial => "/whatson/shared/categories" %>
  <%= render :partial => "/whatson/shared/tags" %>
  <%= render :partial => "/whatson/shared/rss_feed" %>
  <%= render :partial => "/whatson/shared/archive_list" %>
<% end %>

<%= render :partial => "/shared/content_page" %>
<% content_for :stylesheets, stylesheet_link_tag('refinerycms-whatson') %>

app/views/whatson/posts/index.html.erb
<% content_for :body_content_left do %>
  <%=raw @page[Page.default_parts.first.to_sym] if Page.default_parts.any? %>

  <% if @whatson_posts.any? %>
    <section id="whatson_posts">
      <%= render :partial => "/whatson/shared/post", :collection => @whatson_posts %>
      <%= will_paginate @whatson_posts %>
    </section>
  <% else %>
    <p><%= t('.no_whatson_articles_yet') %></p>
  <% end %>
<% end %>

<% content_for :body_content_right do %>
  <%=raw @page[Page.default_parts.second.to_sym] if Page.default_parts.many? %>

  <%= render :partial => "/whatson/shared/categories" %>
  <%= render :partial => "/whatson/shared/tags" %>
  <%= render :partial => "/whatson/shared/rss_feed" %>
  <%= render :partial => "/whatson/shared/archive_list" %>
<% end %>

<%= render :partial => "/shared/content_page" %>
<% content_for :stylesheets, stylesheet_link_tag('refinerycms-whatson') %>

app/views/whatson/posts/show.html.erb
<% content_for :body_content_left do %>
  <div id="show_whatson_post">
    <% flash.each do |key, value| %>
     <div id='flash' class="flash flash_<%= key %>">
       <%= value %>
     </div>
    <% end %>
    <article id="whatson_post">
      <header>
        <h1><%= @whatson_post.title %></h1>
        <section class='details'>
          <time datetime="<%=l @whatson_post.published_at.to_date, :format => :default %>" class='posted_at'>
            <%= t('created_at', :scope => 'whatson.shared.posts', :when => l(@whatson_post.published_at.to_date, :format => :short)) %>
          </time>
          <%= "#{t('by', :scope => 'whatson.posts.show')} #{@whatson_post.author.username}" if @whatson_post.author.present? %>.
          <% if (categories = @whatson_post.categories).any? %>
            <aside class='filed_in'>
              <%= t('filed_in', :scope => 'whatson.posts.show') %>
              <% categories.each_with_index do |category, index| %>
                <%= link_to category.title, whatson_category_url(category) -%><%= ',' if index < ((categories.length) - 1) %>
              <% end %>
            </aside>
          <% end %>
        </section>
      </header>
      <%= @whatson_post.body.html_safe %>

      <% if WhatsonPost::ShareThis.enabled? %>
        <span class="st_sharethis" displayText="ShareThis"></span>
      <% end %>
    </article>
    <%= render :partial => '/shared/draft_page_message' unless @whatson_post.nil? or @whatson_post.live? -%>
    <%= render 'nav' if next_or_previous?(@whatson_post) %>
    
  </div>

  <% if WhatsonPost.comments_allowed? %>
    <aside id="comments">
      <h2><%= t('.comments.title') %></h2>
      <% if (comments = @whatson_post.comments.approved).any? %>
        <%= render :partial => "comment", :collection => comments %>
      <% else %>
        <p>
          <%= t('none', :scope => 'whatson.shared.comments') %>.
        </p>
      <% end %>

      <% flash.each do |key, value| %>
        <div id='flash' class="flash flash_<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <h2><%= t('.comments.add') %></h2>
      <%= form_for [:whatson_post, @whatson_comment] do |f| %>
        <%= render :partial => "/shared/admin/error_messages",
                   :locals => {
                     :object => f.object,
                     :include_object_name => true
                   } %>
        <div class='field'>
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class='field'>
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
        <div class='field message_field'>
          <%= f.label :message %>
          <%= f.text_area :message, :rows => 6 %>
        </div>
        <div class='field form-actions'>
          <%= f.submit t('.submit') %>
        </div>
      <% end %>
    </aside>
  <% end %>
<% end %>

<% content_for :body_content_right do %>
  <%= render :partial => "/whatson/shared/categories" %>
  <%= render :partial => "/whatson/shared/tags" %>
  <%= render :partial => "/whatson/shared/related_posts" %>
  <%= render :partial => "/whatson/shared/rss_feed" %>
  <%= render :partial => "/whatson/shared/archive_list" %>
<% end %>

<%= render :partial => "/shared/content_page", :locals => { :remove_automatic_sections => true }  %>

<% content_for :stylesheets, stylesheet_link_tag('refinerycms-whatson') %>
<% content_for :before_javascript_libraries, jquery_include_tags(:jquery_ui => false) %>
<% content_for :javascripts do %>
  <%# enable AJAX'd post nav at your own risk until html5 history API implemented. %>
  <%#= javascript_include_tag('refinerycms-whatson') %>
  <script src="http://w.sharethis.com/button/buttons.js"></script>
  <script>stLight.options({publisher:'<%= WhatsonPost::ShareThis.key %>'});</script>
<% end if WhatsonPost::ShareThis.enabled? %>

app/views/whatson/posts/tagged.html.erb
<% content_for :body_content_title, "#{t('.posts_tagged')} &#8220;#{@tag_name.titleize}&#8221;".html_safe -%>

<% content_for :body_content_left do %>
  <% if @whatson_posts.any? %>
    <section id="whatson_posts">
      <%= render :partial => "/whatson/shared/post", :collection => @whatson_posts %>
      <%= will_paginate @whatson_posts %>
    </section>
  <% else %>
    <p><%= t('.no_whatson_articles_yet') %></p>
  <% end %>
<% end %>

<% content_for :body_content_right do %>
  <%= render :partial => "/whatson/shared/categories" %>
  <%= render :partial => "/whatson/shared/tags" %>
  <%= render :partial => "/whatson/shared/rss_feed" %>
  <%= render :partial => "/whatson/shared/archive_list" %>
<% end %>

<%= render :partial => "/shared/content_page" %>
<% content_for :stylesheets, stylesheet_link_tag('refinerycms-whatson') %>