config/routes.rb
::Refinery::Application.routes.draw do
  scope(:path => 'whatson', :module => 'whatson') do
    root :to => 'posts#index', :as => 'whatson_root'
    match 'feed.rss', :to => 'posts#index', :as => 'whatson_rss_feed', :defaults => {:format => "rss"}
    match ':id', :to => 'posts#show', :as => 'whatson_post'
    match 'categories/:id', :to => 'categories#show', :as => 'whatson_category'
    match ':id/comments', :to => 'posts#comment', :as => 'whatson_post_whatson_comments'
    get 'archive/:year(/:month)', :to => 'posts#archive', :as => 'archive_whatson_posts'
    get 'tagged/:tag_id(/:tag_name)' => 'posts#tagged', :as => 'tagged_posts'
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    scope(:path => 'whatson', :as => 'whatson', :module => 'whatson') do
      root :to => 'posts#index'
      resources :posts do
        collection do
          get :uncategorized
          get :tags
        end
      end

      resources :categories

      resources :comments do
        collection do
          get :approved
          get :rejected
        end
        member do
          get :approved
          get :rejected
        end
      end

      resources :settings do
        collection do
          get :notification_recipients
          post :notification_recipients

          get :moderation
          get :comments
          get :teasers
        end
      end
    end
  end
end

app/models/whatson/comment_mailer.rb
require File.expand_path('../../../mailers/whatson/comment_mailer', __FILE__)

app/controllers/admin/whatson/categories_controller.rb
module Admin
  module Whatson
    class CategoriesController < Admin::BaseController

      crudify :whatson_category,
              :title_attribute => :title,
              :order => 'title ASC'

    end
  end
end

app/controllers/admin/whatson/comments_controller.rb
module Admin
  module Whatson
    class CommentsController < Admin::BaseController

      crudify :whatson_comment,
              :title_attribute => :name,
              :order => 'published_at DESC'

      def index
        @whatson_comments = WhatsonComment.unmoderated
        render :action => 'index'
      end

      def approved
        unless params[:id].present?
          @whatson_comments = WhatsonComment.approved
          render :action => 'index'
        else
          @whatson_comment = WhatsonComment.find(params[:id])
          @whatson_comment.approve!
          flash[:notice] = t('approved', :scope => 'admin.whatson.comments', :author => @whatson_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

      def rejected
        unless params[:id].present?
          @whatson_comments = WhatsonComment.rejected
          render :action => 'index'
        else
          @whatson_comment = WhatsonComment.find(params[:id])
          @whatson_comment.reject!
          flash[:notice] = t('rejected', :scope => 'admin.whatson.comments', :author => @whatson_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

    end
  end
end

app/controllers/admin/whatson/posts_controller.rb
module Admin
  module Whatson
    class PostsController < Admin::BaseController
      require 'will_paginate/array'
      
      crudify :whatson_post,
              :title_attribute => :title,
              :order => 'published_at DESC'
          
      def uncategorized
        @whatson_posts = WhatsonPost.uncategorized.paginate({
          :page => params[:page],
          :per_page => WhatsonPost.per_page
        })
      end
  
      def tags
        op =  case ActiveRecord::Base.connection.adapter_name.downcase
              when 'postgresql'
                '~*'
              else
                'LIKE'
              end
        wildcard =  case ActiveRecord::Base.connection.adapter_name.downcase
                    when 'postgresql'
                      '.*'
                    else
                      '%'
                    end
        @tags = WhatsonPost.tag_counts_on(:tags).where(
            ["tags.name #{op} ?", "#{wildcard}#{params[:term].to_s.downcase}#{wildcard}"]
          ).map { |tag| {:id => tag.id, :value => tag.name}}
        render :json => @tags.flatten
      end
  
      def create
        # if the position field exists, set this object as last object, given the conditions of this class.
        if WhatsonPost.column_names.include?("position")
          params[:whatson_post].merge!({
            :position => ((WhatsonPost.maximum(:position, :conditions => "")||-1) + 1)
          })
        end
    
        if WhatsonPost.column_names.include?("user_id")
          params[:whatson_post].merge!({
            :user_id => current_user.id
          })
        end

        if (@whatson_post = WhatsonPost.create(params[:whatson_post])).valid?
          (request.xhr? ? flash.now : flash).notice = t(
            'refinery.crudify.created',
            :what => "'#{@whatson_post.title}'"
          )

          unless from_dialog?
            unless params[:continue_editing] =~ /true|on|1/
              redirect_back_or_default(admin_whatson_posts_url)
            else
              unless request.xhr?
                redirect_to :back
              else
                render :partial => "/shared/message"
              end
            end
          else
            render :text => "<script>parent.window.location = '#{admin_whatson_posts_url}';</script>"
          end
        else
          unless request.xhr?
            render :action => 'new'
          else
            render :partial => "/shared/admin/error_messages",
                   :locals => {
                     :object => @whatson_post,
                     :include_object_name => true
                   }
          end
        end
      end

      before_filter :find_all_categories,
                    :only => [:new, :edit, :create, :update]

      before_filter :check_category_ids, :only => :update

    protected
      def find_all_categories
        @whatson_categories = WhatsonCategory.find(:all)
      end

      def check_category_ids
        params[:whatson_post][:category_ids] ||= []
      end
    end
  end
end

app/controllers/admin/whatson/settings_controller.rb
module Admin
  module Whatson
    class SettingsController < Admin::BaseController

      def notification_recipients
        @recipients = WhatsonComment::Notification.recipients

        if request.post?
          WhatsonComment::Notification.recipients = params[:recipients]
          flash[:notice] = t('updated', :scope => 'admin.whatson.settings.notification_recipients',
                             :recipients => WhatsonComment::Notification.recipients)
          unless request.xhr? or from_dialog?
            redirect_back_or_default(admin_whatson_posts_path)
          else
            render :text => "<script type='text/javascript'>parent.window.location = '#{admin_whatson_posts_path}';</script>",
                   :layout => false
          end
        end
      end

      def moderation
        enabled = WhatsonComment::Moderation.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

      def comments
        enabled = WhatsonComment.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end
      
      def teasers
        enabled = WhatsonPost.teaser_enabled_toggle!
        unless request.xhr?
          redirect_back_or_default(admin_whatson_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

    end
  end
end

app/controllers/whatson/categories_controller.rb
module Whatson
  class CategoriesController < WhatsonController

    def show
      @category = WhatsonCategory.find(params[:id])
      @whatson_posts = @category.posts.live.includes(:comments, :categories).paginate({
        :page => params[:page],
        :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
      })
    end

  end
end

app/controllers/whatson/posts_controller.rb
module Whatson
  class PostsController < WhatsonController

    before_filter :find_all_whatson_posts, :except => [:archive]
    before_filter :find_whatson_post, :only => [:show, :comment, :update_nav]
    before_filter :find_tags

    respond_to :html, :js, :rss

    def index
      # Rss feeders are greedy. Let's give them every whatson post instead of paginating.
      (@whatson_posts = WhatsonPost.live.includes(:comments, :categories).all) if request.format.rss?
      respond_with (@whatson_posts) do |format|
        format.html
        format.rss
      end
    end

    def show
      @whatson_comment = WhatsonComment.new
      @canonical = url_for(:locale => ::Refinery::I18n.default_frontend_locale) if canonical?

      respond_with (@whatson_post) do |format|
        format.html { present(@whatson_post) }
        format.js { render :partial => 'post', :layout => false }
      end
    end

    def comment
      if (@whatson_comment = @whatson_post.comments.create(params[:whatson_comment])).valid?
        if WhatsonComment::Moderation.enabled? or @whatson_comment.ham?
          begin
            Whatson::CommentMailer.notification(@whatson_comment, request).deliver
          rescue
            logger.warn "There was an error delivering a whatson comment notification.\n#{$!}\n"
          end
        end

        if WhatsonComment::Moderation.enabled?
          flash[:notice] = t('thank_you_moderated', :scope => 'whatson.posts.comments')
          redirect_to whatson_post_url(params[:id])
        else
          flash[:notice] = t('thank_you', :scope => 'whatson.posts.comments')
          redirect_to whatson_post_url(params[:id],
                                   :anchor => "comment-#{@whatson_comment.to_param}")
        end
      else
        render :action => 'show'
      end
    end

    def archive
      if params[:month].present?
        date = "#{params[:month]}/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%B %Y')
        @whatson_posts = WhatsonPost.live.by_archive(@archive_date).paginate({
                                                                               :page => params[:page],
                                                                               :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                             })
      else
        date = "01/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%Y')
        @whatson_posts = WhatsonPost.live.by_year(@archive_date).paginate({
                                                                            :page => params[:page],
                                                                            :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                          })
      end
      respond_with (@whatson_posts)
    end

    def tagged
      @tag = ActsAsTaggableOn::Tag.find(params[:tag_id])
      @tag_name = @tag.name
      @whatson_posts = WhatsonPost.tagged_with(@tag_name).paginate({
                                                                     :page => params[:page],
                                                                     :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                   })
    end

    protected

    def find_whatson_post
      unless (@whatson_post = WhatsonPost.find(params[:id])).try(:live?)
        if refinery_user? and current_user.authorized_plugins.include?("refinerycms_whatson")
          @whatson_post = WhatsonPost.find(params[:id])
        else
          error_404
        end
      end
    end

    def find_all_whatson_posts
      @whatson_posts = WhatsonPost.live.includes(:comments, :categories).paginate({
                                                                                    :page => params[:page],
                                                                                    :per_page => RefinerySetting.find_or_set(:whatson_posts_per_page, 10)
                                                                                  })
    end

    def find_tags
      @tags = WhatsonPost.tag_counts_on(:tags)
    end

    def canonical?
      ::Refinery.i18n_enabled? && ::Refinery::I18n.default_frontend_locale != ::Refinery::I18n.current_frontend_locale
    end
  end
end

app/controllers/whatson_controller.rb
class WhatsonController < ApplicationController

  helper :whatson_posts
  before_filter :find_page, :find_all_whatson_categories

protected

  def find_page
    @page = Page.find_by_link_url("/whatson")
  end

  def find_all_whatson_categories
    @whatson_categories = WhatsonCategory.all
  end

end

app/views/admin/whatson/posts/_form.css.erb
<style type='text/css'>
  ul.whatson_categories{
    height:200px;
    overflow:auto;
    border:1px solid #ccc;
    padding:5px;
  }
  ul.whatson_categories, ul.whatson_categories li {
    list-style: none;
    margin:5px 0;
  }
  a#copy_body_link {
    background: url("/images/refinery/icons/add.png") no-repeat scroll 0 6px transparent;
    border-bottom: 0 none;
    display: inline;
    line-height: 29px;
    margin-top: 0;
    padding-left: 20px;
  }
</style>

app/views/admin/whatson/posts/_form.html.erb
<%= form_for [:admin, @whatson_post] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => f.object,
               :include_object_name => true
             } %>

  <div class='field'>
    <%= f.label :title -%>
    <%= f.text_field :title, :class => 'larger widest' -%>
  </div>
  <div class="field">
    <p>
      <%= f.check_box :draft %>
      <%= f.label :draft, t('.save_as_draft'), :class => "stripped" %>
    </p>
  </div>
  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <li class='ui-state-default ui-state-active'>
          <%= link_to t('body', :scope => 'activerecord.attributes.whatson_post'), "#page_part_body" %>
        </li>
        <li class='ui-state-default'>
          <%= link_to t('teaser', :scope => 'activerecord.attributes.whatson_post'), "#page_part_teaser" %>
        </li>
        <% Refinery::Whatson.tabs.each_with_index do |tab, tab_index| %>
          <li class='ui-state-default' id="custom_<%= tab.name %>_tab">
            <%= link_to tab.name.titleize, "#custom_tab_#{tab_index}" %>
          </li>
        <% end %>
      </ul>
      
      <div id='page_part_editors'>
      
        <% part_index = -1 %>
          <%= render :partial => 'form_part',
                     :locals => {
                       :f => f,
                       :part_index => (part_index += 1),
                     } -%>
          <%= render :partial => 'teaser_part',
                     :locals => {
                       :f => f,
                       :part_index => (part_index += 1),
                     } if f.object.respond_to?(:custom_teaser) -%>
        <% Refinery::Whatson.tabs.each_with_index do |tab, tab_index| %>
          <div class='page_part' id='<%= "custom_tab_#{tab_index}" %>'>
            <%= render :partial => tab.partial, :locals => {:f => f} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class='field'>
    <%= f.label :tag_list, t('whatson.shared.tags.title') -%>
    <%= f.text_field :tag_list, :class => 'larger' -%>
  </div>
  
  <div id='more_options_field'>
    <p>
      <%= link_to t('.advanced_options'), "#",
                  :id => 'toggle_advanced_options',
                  :title => t('.toggle_advanced_options') %>
    </p>
    
  </div>
  <div id='more_options' style="display:none;">
    <div class="hemisquare">
      <h3><%= t('title', :scope => 'admin.whatson.submenu.categories') %></h3>
      <ul class='whatson_categories'>
        <% @whatson_categories.each do |category| %>
          <li>
             <%= check_box_tag 'whatson_post[category_ids][]', category.id,
                               @whatson_post.categories.include?(category),
                               :id => (id="whatson_post_category_ids_#{category.id}") %>
             <%= label_tag 'whatson_post[category_ids][]', category.title,
                           :class => 'stripped',
                           :for => id %>
          </li>
        <% end %>
      </ul>
      <h3><%= t('.published_at') %></h3>
      <%= f.datetime_select :published_at %>

      <div class='field'>
        <span class='label_with_help'>
          <%= f.label :custom_url, t('.custom_url') %>
          <%= refinery_help_tag t('.custom_url_help') %>
        </span>
        <%= f.text_field :custom_url, :class => "widest" %>
      </div>

    </div>
    <div class='hemisquare right_side'>
      <%= render :partial => '/seo_meta/form', :locals => {:form => f} %>
    </div>
  </div>
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => true,
                :delete_title => t('delete', :scope => 'admin.whatson.posts.post')
              } %>
<% end -%>

<% content_for :stylesheets, render(:partial => 'form.css') -%>
<% content_for :javascripts, render(:partial => 'form.js') -%>
<%= render 'shared/admin/autocomplete', :dom_id => '#whatson_post_tag_list', :url => tags_admin_whatson_posts_url %>

app/views/admin/whatson/posts/_form.js.erb
<script>
  (function($) {
    $(function() {
      $('#page-tabs').tabs();
      $('#copy_body_link').click(function(event) {
        // Find the WYMEditor that maps to the custom_teaser field
        var teaserTextArea = $('#whatson_post_custom_teaser')[0];
        var teaserEditor = null;
        $.each(WYMeditor.INSTANCES, function(index, editor) {
          if (editor._element[0] == teaserTextArea) {
            teaserEditor = editor;
          }
        });

        if (teaserEditor) {
          teaserEditor.html($('#whatson_post_body').attr('value'));
        }

        event.preventDefault();
      });
    });
  })(jQuery);
</script>

app/views/admin/whatson/posts/_form_part.html.erb
<div class='page_part' id='page_part_body'>
  <%= f.text_area :body, :rows => 20, :class => 'wymeditor widest' -%>
</div>

app/views/admin/whatson/posts/_post.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(post) -%>">
  <span class='title'>
    <%= post.title %>
    <span class="preview">
      <%= post.published_at.try(:strftime, '%b %d, %Y') || 'draft' %>
      <%= " by #{post.author.username}" if post.author.present? %>
    </span>
  </span>
  <% if post.draft? %>
    <span class="label notice">Draft</span>
  <% end %>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), whatson_post_url(post),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_whatson_post_path(post),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_whatson_post_path(post),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :method => :delete,
        :confirm => t('message', :scope => 'shared.admin.delete', :title => post.title) %>
  </span>
</li>

app/views/admin/whatson/posts/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'post', :collection => @whatson_posts %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
           :locals => {
             :continue_reordering => (defined?(continue_reordering) ? continue_reordering : true)
           } %>

app/views/admin/whatson/posts/_teaser_part.html.erb
<div class='page_part' id='page_part_teaser'>
  <%= f.text_area :custom_teaser, :rows => 20, :class => 'wymeditor widest' -%>
  <p>
    <span class='clearfix label_inline_with_link'>
      <%= link_to t('copy_body', :scope => 'admin.whatson.posts.form'), "#",
                  :id => 'copy_body_link',
                  :title => t('copy_body_help', :scope => 'admin.whatson.posts.form') %>
    </span>
  </p>
</div>

app/views/admin/whatson/posts/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/whatson/posts/index.html.erb
<%= render :partial => '/admin/whatson/submenu' %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
    <% if @whatson_posts.any? %>
    <ul>
      <%= render :partial => "post",
                 :collection => @whatson_posts %>
    </ul>
    <% else %>
      <p><%= t('no_results', :scope => 'shared.admin.search') %></p>
    <% end %>
  <% else %>
    <% if @whatson_posts.any? %>
      <%= will_paginate @whatson_posts %>

      <%= render :partial => "sortable_list" %>

      <%= will_paginate @whatson_posts %>
    <% else %>
      <p>
        <strong>
          <%= t('.no_items_yet', :create => t('new', :scope => 'admin.whatson.submenu.posts')) %>
        </strong>
      </p>
    <% end %>
  <% end %>
</div>

app/views/admin/whatson/posts/new.html.erb
<%= render :partial => "form" %>

app/views/admin/whatson/posts/uncategorized.html.erb
<%= render :partial => '/admin/whatson/submenu' %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
    <% if @whatson_posts.any? %>
      <%= render :partial => "whatson_posts",
                 :collection => @whatson_posts %>
    <% else %>
      <p><%= t('search_no_results', :scope => 'admin') %></p>
    <% end %>
  <% else %>
    <% if @whatson_posts.any? %>
      <%= will_paginate @whatson_posts %>

      <%= render :partial => "sortable_list" %>

      <%= will_paginate @whatson_posts %>
    <% else %>
      <p>
        <strong>
          <%= t('.no_items_yet', :create => t('new', :scope => 'admin.whatson.submenu.posts')) %>
        </strong>
      </p>
    <% end %>
  <% end %>
</div>